application: peterhofguide
version: live
runtime: python27
api_version: 1
threadsafe: false

default_expiration: "7d"

libraries:
- name: django
  version: "1.2"

handlers:
- url: /styles
  static_dir: static/css

- url: /scripts
  static_dir: static/js

- url: /images
  static_dir: static/img

- url: /templates
  static_dir: static/templates

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /gss.xsl
  static_files: static/gss.xsl
  upload: static/gss.xsl
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /service/.*
  script: service_handler.py

- url: /.*
  script: web_handler.py